modLoader = "javafml"
loaderVersion = "[30,)"

authors = "chylex"
issueTrackerURL = "https://github.com/chylex/Better-Sprinting/issues"

[[mods]]
modId = "bettersprinting"
version = "3.0.1a"
displayName = "Better Sprinting"
displayURL = "https://bsprint.chylex.com"
updateJSONURL = "https://raw.githubusercontent.com/chylex/Better-Sprinting/master/UpdateInfo.json"
logoFile = "logo.png"
description = '''
New ways to control sprinting, sneaking, and flying.

To configure the mod, click the Better Sprinting button in Controls, or press the configuration key in-game (default: 'O').

Find me on Twitter: https://twitter.com/chylexmc
'''

[[dependencies.bettersprinting]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.15.1]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.bettersprinting]]
    modId = "forge"
    mandatory = true
    versionRange = "[30,)"
    ordering = "NONE"
    side = "BOTH"
